import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id:uuid(),
    id: 1,
    title: "Diamond Pendant Necklace",
    image: "./images/braceletp1.jpg",
    description: "This exquisite diamond pendant necklace features a stunning solitaire diamond set in a delicate 14k white gold chain.",
    category: "Necklace",
    price: 199.99,
    original_price: 249.99,
    stars: 4.5,
    quantity: 1,
  },
  {
    _id:uuid(),
    id: 2,
    title: "Pearl Choker Necklace",
    image: "./images/necklaceP2.jpg",
    description: "Enhance your neckline with this timeless pearl choker necklace.",
    category:"Necklace",
    price: 149.99,
    original_price: 199.99,
    stars: 3.9,
    quantity: 1,
  },
  {
    _id:uuid(),
    id: 3,
    title: "Gold Heart Pendant Necklace",
    image: "./images/necklaceP3.jpg",
    description: "Express your love with this delicate rose gold heart pendant necklace.",
    category: "Necklace",
    price: 179.99,
    original_price: 229.99,
    stars: 4.7,
    quantity: 1,
  },
  {
    _id:uuid(),
    id: 4,
    title: "Cubic Zirconia Tennis Necklace",
    image: "./images/necklaceP4.jpg",
    description: "Get the glamorous look with this stunning cubic zirconia tennis necklace.",
    category: "Necklace",
    price: 129.99,
    original_price: 149.99,
    stars: 2.4,
    quantity: 1,
  },
  {
    _id:uuid(),
    id: 5,
    title: "Silver Infinity Pendant Necklace",
    image: "./images/necklaceP5.jpg",
    description: "Symbolize eternal love and infinite possibilities with this beautiful silver infinity pendant necklace.",
    category: "Necklace",
    price: 89.99,
    original_price: 119.99,
    stars: 3.6,
    quantity: 1,
  },
  {
    _id:uuid(),
    id: 6,
    title: "Birthstone Bar Necklace",
    image: "./images/necklaceP6.jpg",
    description: "Celebrate your birth month with this personalized birthstone bar necklace.",
    category: "Necklace",
    price: 109.99,
    original_price: 139.99,
    stars: 4.3,
    quantity: 1,
  },
  {
    _id:uuid(),
    id: 7,
    title: "Crystal Pendant Necklace",
    image: "./images/necklaceP7.jpg",
    description: "Add a touch of sparkle to your look with this Swarovski crystal pendant necklace.",
    category: "Necklace",
    price: 139.99,
    original_price: 189.99,
    stars: 4.8,
    quantity: 1,
  },
  // Bracelets
  {
    _id:uuid(),
    id: 8,
    title: "Silver Infinity Bracelet",
    image: "./images/braceletP1.jpg",
    description: "Symbolize eternal love with this elegant silver infinity bracelet.",
    category: "Bracelet",
    price: 79.99,
    original_price: 99.99,
    stars: 2.7,
    quantity: 1,
  },
  {
    _id:uuid(),
    id: 9,
    title: "Gemstone Beaded Bracelet Set",
    image: "./images/braceletP2.jpg",
    description: "Add a pop of color to your wrist with this trendy gemstone beaded bracelet set.",
    category: "Bracelet",
    price: 59.99,
    original_price: 89.99,
    stars: 3.3,
    quantity: 1,
  },
  {
    _id:uuid(),
    id: 10,
    title: "Rose Gold Cuff Bracelet",
    image: "./images/braceletP3.jpg",
    description: "Make a statement with this chic rose gold cuff bracelet.",
    category: "Bracelet",
    price: 89.99,
    original_price: 119.99,
    stars: 4.5,
    quantity: 1,
  },
  {
    _id:uuid(),
    id: 11,
    title: "Diamond Bangle Bracelet",
    image: "./images/braceletP4.jpg",
    description: "Elevate your style with this stunning pearl and diamond bangle bracelet.",
    category: "Bracelet",
    price: 199.99,
    original_price: 249.99,
    stars: 4.8,
    quantity: 1,
  },
  {
    _id:uuid(),
    id: 12,
    title: "Leather Wrap Bracelet",
    image: "./images/braceletP5.jpg",
    description: "Add a touch of boho charm to your wrist with this stylish leather wrap bracelet.",
    category: "Bracelet",
    price: 39.99,
    original_price: 49.99,
    stars: 2.2,
    quantity: 1,
  },
  {
    _id:uuid(),
    id: 13,
    title: "Diamond Tennis Bracelet",
    image: "./images/braceletP6.jpg",
    description: "Get the ultimate sparkle with this exquisite diamond tennis bracelet.",
    category: "Bracelet",
    price: 499.99,
    original_price: 549.99,
    stars: 4.9,
    quantity: 1,
  },
  {
    _id:uuid(),
    id: 14,
    title: "Silver Charm Bracelet",
    image: "./images/braceletP7.jpg",
    description: "Create your own story with this versatile silver charm bracelet.",
    category: "Bracelet",
    price: 69.99,
    original_price: 99.99,
    stars: 3.4,
    quantity: 1,
  },

  // Earrings
  {
    _id:uuid(),
    id: 15,
    title: "Diamond Stud Earrings",
    image: "./images/earringP1.jpg",
    description: "Classic and timeless, these diamond stud earrings are a must-have for every jewelry collection.",
    category: "Earrings",
    price: 299.99,
    original_price: 349.99,
    stars: 4.6,
    quantity: 1,
  },
  {
    _id:uuid(),
    id: 16,
    title: "Pearl Drop Earrings",
    image: "./images/earringP2.jpg",
    description: "Add a touch of elegance to your look with these stunning pearl drop earrings.",
    category: "Earrings",
    price: 89.99,
    original_price: 139.99,
    stars: 3.3,
    quantity: 1,
  },
  {
    _id:uuid(),
    id:17,
    title: "Hoop Earrings",
    image: "./images/earringP3.jpg",
    description: "Complete your outfit with these classic hoop earrings.",
    category: "Earrings",
    price: 49.99,
    original_price: 69.99,
    stars: 2.2,
    quantity: 1,
  },
  {
    _id:uuid(),
    id: 18,
    title: "Cubic Zirconia Stud Earrings",
    image: "./images/earringP4.jpg",
    description: "Get the look of diamonds at an affordable price with these sparkling cubic zirconia stud earrings.",
    category: "Earrings",
    price: 69.99,
    original_price: 89.99,
    stars: 4.4,
    quantity: 1,
  },
  {
    _id:uuid(),
    id: 19,
    title: "Rose Gold Dangle Earrings",
    image: "./images/earringP5.jpg",
    description: "Make a statement with these eye-catching rose gold dangle earrings.",
    category: "Earrings",
    price: 129.99,
    original_price: 149.99,
    stars: 4.8,
    quantity: 1,
  },
  {
    _id:uuid(),
    id: 20,
    title: "Diamond Cluster Stud Earrings",
    image: "./images/earringP6.jpg",
    description: "Sparkle and shine with these exquisite diamond cluster stud earrings.",
    category: "Earrings",
    price: 199.99,
    original_price: 249.99,
    stars: 4.7,
    quantity: 1,
  },
  {
    _id:uuid(),
    id: 21,
    title: "Sterling Silver Hoop Earrings",
    image: "./images/earringP7.jpg",
    description: "Add a touch of elegance to your look with these sterling silver hoop earrings.",
    category: "Earrings",
    price: 59.99,
    original_price: 99.99,
    stars: 4.5,
    quantity: 1,
  },

  // Rings
  {
    _id:uuid(),
    id: 22,
    title: "Diamond Engagement Ring",
    image: "./images/ringP1.jpg",
    description: "Pop the question with this stunning diamond engagement ring.",
    category: "Ring",
    price: 749.99,
    original_price: 799.99,
    stars: 4.9,
    quantity: 1,
  },
  {
    _id:uuid(),
    id: 23,
    title: "Sterling Silver Birthstone Ring",
    image: "./images/ringP2.jpg",
    description: "Celebrate your birth month with this elegant sterling silver birthstone ring.",
    category: "Ring",
    price: 79.99,
    original_price: 99.99,
    stars: 4.5,
    quantity: 1,
  },
  {
    _id:uuid(),
    id: 24,
    title: "Rose Gold Stackable Ring Set",
    image: "./images/ringP3.jpg",
    description: "Mix and match these dainty rose gold stackable rings for a personalized look.",
    category: "Ring",
    price: 129.99,
    original_price: 149.99,
    stars: 4.7,
    quantity: 1,
  },
  {
    _id:uuid(),
    id: 25,
    title: "Diamond Wedding Band",
    image: "./images/ringP4.jpg",
    description: "Complete your bridal set with this exquisite diamond wedding band.",
    category: "Ring",
    price: 699.99,
    original_price: 749.99,
    stars: 4.8,
    quantity: 1,
  },
  {
    _id:uuid(),
    id: 26,
    title: "Cushion-Cut Gemstone Ring",
    image: "./images/ringP5.jpg",
    description: "Make a bold statement with this stunning cushion-cut gemstone ring.",
    category: "Ring",
    price: 299.99,
    original_price: 349.99,
    stars: 4.6,
    quantity: 1,
  },
  {
    _id:uuid(),
    id: 27,
    title: "Pearl and Diamond Ring",
    image: "./images/ringP6.jpg",
    description: "Add a touch of elegance to your look with this pearl and diamond ring.",
    category: "Ring",
    price: 149.99,
    original_price: 199.99,
    stars: 3.4,
    quantity: 1,
  },
  {
    _id:uuid(),
    id: 28,
    title: "Rose Gold Eternity Band",
    image: "./images/ringP7.jpg",
    description: "Symbolize everlasting love with this beautiful rose gold eternity band.",
    category: "Ring",
    price: 499.99,
    original_price: 549.99,
    stars: 4.7,
    quantity: 1,
  }
];
